lex_error4.py returned with 1

Traceback (most recent call last):
  ...
SyntaxError: Can't build lexer

ERROR: /home/herczy/devel/ply/test/lex_error4.py:20: Rule 't_error' has too many arguments
